In [1]:
from keras.layers import Convolution2D

Using TensorFlow backend.


In [2]:
from keras.layers import MaxPooling2D

In [3]:
from keras.layers import Flatten

In [4]:
from keras.layers import Dense

In [5]:
from keras.models import Sequential 

In [6]:
model=Sequential() 

In [7]:
model.add(Convolution2D(filters=32,
                       kernel_size=(3,3), 
                        activation='relu',
                   input_shape=(64, 64, 3)
                       ))

In [8]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 32)        896       
Total params: 896
Trainable params: 896
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.add(MaxPooling2D(pool_size=(2, 2)))

In [10]:
model.add(Convolution2D(filters=32,
                       kernel_size=(3,3), 
                        activation='relu',
                   ))

In [11]:
model.add(MaxPooling2D(pool_size=(2, 2)))

In [12]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 14, 14, 32)        0         
Total params: 10,144
Trainable params: 10,144
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.add(Flatten())

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 6272)              0         
Total params: 10,144
Trainable params: 10,144
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.add(Dense(units=128, activation='relu'))

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 6272)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               802944    
Total params: 813,088
Trainable params: 813,088
Non-trainable params: 0
________________________________________________

In [17]:
model.add(Dense(units=1, activation='sigmoid'))

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 6272)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               802944    
_________________________________________________________________
dense_2 (Dense)              (None, 1)                

In [19]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [20]:
from keras_preprocessing.image import ImageDataGenerator

In [21]:
train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)
test_datagen = ImageDataGenerator(rescale=1./255)
training_set = train_datagen.flow_from_directory(
        'images/Train/',
        target_size=(64, 64),
        batch_size=32,
        class_mode='binary')
test_set = test_datagen.flow_from_directory(
        'images/Test/',
        target_size=(64, 64),
        batch_size=32,
        class_mode='binary')
model.fit(
        training_set,
        steps_per_epoch=140,
        epochs=25,
        validation_data=test_set,
        validation_steps=800)

Found 122 images belonging to 2 classes.
Found 18 images belonging to 2 classes.
Epoch 1/25
140/140 [==============================] - 122s 869ms/step - loss: 0.1156 - accuracy: 0.9534 - val_loss: 0.0032 - val_accuracy: 1.0000
Epoch 2/25
140/140 [==============================] - 155s 1s/step - loss: 0.0205 - accuracy: 0.9946 - val_loss: 0.0139 - val_accuracy: 1.0000
Epoch 3/25
140/140 [==============================] - 202s 1s/step - loss: 0.0066 - accuracy: 0.9984 - val_loss: 7.6201e-04 - val_accuracy: 1.0000
Epoch 4/25
140/140 [==============================] - 210s 2s/step - loss: 0.0039 - accuracy: 0.9993 - val_loss: 3.9946e-04 - val_accuracy: 1.0000
Epoch 5/25
140/140 [==============================] - 221s 2s/step - loss: 0.0125 - accuracy: 0.9951 - val_loss: 6.5317e-05 - val_accuracy: 1.0000
Epoch 6/25
140/140 [==============================] - 205s 1s/step - loss: 0.0014 - accuracy: 0.9998 - val_loss: 6.0781e-05 - val_accuracy: 1.0000
Epoch 7/25
140/140 [======================

In [57]:
from keras.preprocessing import image

In [58]:
test_image = image.load_img('Test/covid/0.jpeg', 
               target_size=(64,64))

In [59]:
type(test_image)

PIL.Image.Image

In [60]:
test_image=image.img_to_array(test_image)

In [61]:
test_image.shape

(64, 64, 3)

In [62]:
import numpy as np

In [63]:
test_image=np.expand_dims(test_image,axis=0)

In [64]:
test_image.shape

(1, 64, 64, 3)

In [65]:
result = model.predict(test_image)

In [66]:
result

array([[0.]], dtype=float32)

In [67]:
result = training_set.class_indices

In [68]:
result

{'covid': 0, 'non-covid': 1}

In [69]:
if result[0][0] == 1.0:
    print('non-covid')
else:
    print('covid')

KeyError: 0

In [70]:
test_image = image.load_img('Test/non-covid/0.jpeg', 
               target_size=(64,64))
type(test_image)
test_image=image.img_to_array(test_image)
test_image.shape
test_image=np.expand_dims(test_image,axis=0)
test_image.shape
result = model.predict(test_image)
result

array([[1.]], dtype=float32)

In [71]:
if result[0][0] == 1.0:
    print('non-covid')
else:
    print('covid')

non-covid


In [72]:
test_image = image.load_img('Test/non-covid/1.jpeg', 
               target_size=(64,64))
type(test_image)
test_image=image.img_to_array(test_image)
test_image.shape
test_image=np.expand_dims(test_image,axis=0)
test_image.shape
result = model.predict(test_image)
result

array([[1.]], dtype=float32)

In [73]:
if result[0][0] == 1.0:
    print('non-covid')
else:
    print('covid')

non-covid


In [74]:
test_image = image.load_img('Test/covid/1.jpeg', 
               target_size=(64,64))
type(test_image)
test_image=image.img_to_array(test_image)
test_image.shape
test_image=np.expand_dims(test_image,axis=0)
test_image.shape
result = model.predict(test_image)
result

array([[0.]], dtype=float32)

In [75]:
if result[0][0] == 1.0:
    print('non-covid')
else:
    print('covid')

covid
