In [1]:
from keras.layers import Convolution2D

Using TensorFlow backend.


In [2]:
from keras.layers import MaxPooling2D

In [3]:
from keras.layers import Flatten

In [4]:
from keras.layers import Dense

In [5]:
from keras.models import Sequential 

In [6]:
model=Sequential() 

In [7]:
model.add(Convolution2D(filters=32,
                       kernel_size=(3,3), 
                        activation='relu',
                   input_shape=(64, 64, 3)
                       ))

In [8]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 32)        896       
Total params: 896
Trainable params: 896
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.add(MaxPooling2D(pool_size=(2, 2)))

In [10]:
model.add(Convolution2D(filters=32,
                       kernel_size=(3,3), 
                        activation='relu',
                   ))

In [11]:
model.add(MaxPooling2D(pool_size=(2, 2)))

In [12]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 14, 14, 32)        0         
Total params: 10,144
Trainable params: 10,144
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.add(Flatten())

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 6272)              0         
Total params: 10,144
Trainable params: 10,144
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.add(Dense(units=128, activation='relu'))

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 6272)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               802944    
Total params: 813,088
Trainable params: 813,088
Non-trainable params: 0
________________________________________________

In [17]:
model.add(Dense(units=1, activation='sigmoid'))

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 6272)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               802944    
_________________________________________________________________
dense_2 (Dense)              (None, 1)                

In [19]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [20]:
from keras_preprocessing.image import ImageDataGenerator

In [21]:
train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)
test_datagen = ImageDataGenerator(rescale=1./255)
training_set = train_datagen.flow_from_directory(
        'images/Train/',
        target_size=(64, 64),
        batch_size=32,
        class_mode='binary')
test_set = test_datagen.flow_from_directory(
        'images/Test/',
        target_size=(64, 64),
        batch_size=32,
        class_mode='binary')
model.fit(
        training_set,
        steps_per_epoch=140,
        epochs=15,
        validation_data=test_set,
        validation_steps=800)

Found 122 images belonging to 2 classes.
Found 18 images belonging to 2 classes.
Epoch 1/15
140/140 [==============================] - 142s 1s/step - loss: 0.1119 - accuracy: 0.9581 - val_loss: 0.1149 - val_accuracy: 0.9444
Epoch 2/15
140/140 [==============================] - 119s 849ms/step - loss: 0.0279 - accuracy: 0.9902 - val_loss: 4.7619e-04 - val_accuracy: 1.0000
Epoch 3/15
140/140 [==============================] - 128s 918ms/step - loss: 0.0031 - accuracy: 0.9995 - val_loss: 1.0212e-04 - val_accuracy: 1.0000
Epoch 4/15
140/140 [==============================] - 121s 864ms/step - loss: 0.0039 - accuracy: 0.9991 - val_loss: 9.1223e-04 - val_accuracy: 1.0000
Epoch 5/15
140/140 [==============================] - 119s 853ms/step - loss: 0.0013 - accuracy: 0.9995 - val_loss: 1.9345e-04 - val_accuracy: 1.0000
Epoch 6/15
140/140 [==============================] - 136s 974ms/step - loss: 0.0096 - accuracy: 0.9965 - val_loss: 2.6159e-04 - val_accuracy: 1.0000
Epoch 7/15
140/140 [======

In [22]:
from keras.preprocessing import image

In [23]:
test_image = image.load_img('Test/covid/0.jpeg', 
               target_size=(64,64))

In [24]:
type(test_image)

PIL.Image.Image

In [25]:
test_image=image.img_to_array(test_image)

In [26]:
test_image.shape

(64, 64, 3)

In [27]:
import numpy as np

In [28]:
test_image=np.expand_dims(test_image,axis=0)

In [29]:
test_image.shape

(1, 64, 64, 3)

In [30]:
result = model.predict(test_image)

In [31]:
result

array([[0.]], dtype=float32)

In [32]:
result = training_set.class_indices

In [33]:
result

{'covid': 0, 'non-covid': 1}

In [34]:
test_image = image.load_img('Test/non-covid/1.jpeg', 
               target_size=(64,64))
type(test_image)
test_image=image.img_to_array(test_image)
test_image.shape
test_image=np.expand_dims(test_image,axis=0)
test_image.shape
result = model.predict(test_image)
result

array([[1.]], dtype=float32)

In [35]:
if result[0][0] == 1.0:
    print('non-covid')
else:
    print('covid')

non-covid


In [36]:
test_image = image.load_img('Test/covid/1.jpeg', 
               target_size=(64,64))
type(test_image)
test_image=image.img_to_array(test_image)
test_image.shape
test_image=np.expand_dims(test_image,axis=0)
test_image.shape
result = model.predict(test_image)
result

array([[0.]], dtype=float32)

In [37]:
if result[0][0] == 1.0:
    print('non-covid')
else:
    print('covid')

covid


In [39]:
model.save('covid.h5')

AttributeError: 'Sequential' object has no attribute 'load'